#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../.." || exit

echo
echo "--------------------------------"
echo "SCALA_VERSION   = $SCALA_VERSION"
echo "SBT_COMMAND     = $SBT_COMMAND"
echo "SCALAJS_VERSION = $SCALAJS_VERSION"
echo "PLATFORM        = $PLATFORM"
echo "--------------------------------"
echo

if [[ -z "$SCALA_VERSION" ]]; then
    echo "ERROR: environment value SCALA_VERSION is not set!" 1>&2
    exit 1
fi

if [[ -z "$SBT_COMMAND" ]]; then
    echo "ERROR: environment value SBT_COMMAND is not set!" 1>&2
    exit 1
fi

if [ $SCALA_VERSION = '2.11.12' ] && [ $SCALAJS_VERSION = '1.0.0' ]
then
    echo "No tests were executed since sjs 1.0.0 and scala 2.11 are not compatible."
elif [ $PLATFORM = '11' ] && ([ $SCALA_VERSION = '2.11.12' ] || [ $SCALA_VERSION = '2.12.11' ])
then
    echo "No tests were executed."
else
   sbt -J-Xmx6144m ++$SCALA_VERSION $SBT_COMMAND
fi
exit 0