#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../.." || exit

echo
echo "--------------------------------"
echo "SCALA_COMMAND   = $SCALA_COMMAND"
echo "SBT_COMMAND     = $SBT_COMMAND"
echo "PLATFORM        = $PLATFORM"
echo "--------------------------------"
echo

if [[ -z "$SCALA_COMMAND" ]]; then
    echo "ERROR: environment value SCALA_COMMAND is not set!" 1>&2
    exit 1
fi

if [[ -z "$SBT_COMMAND" ]]; then
    echo "ERROR: environment value SBT_COMMAND is not set!" 1>&2
    exit 1
fi

sbt -J-Xmx6144m ";$SCALA_COMMAND;$SBT_COMMAND"
