#!/usr/bin/env bash

echo "SCALAJS_VERSION=$SCALAJS_VERSION"
git fetch --depth=100 origin +refs/tags/*:refs/tags/*

if [ "$PUBLISH_STABLE_VERSION" != "true" ]; then
  if [[ "$GITHUB_REF" =~ ^v[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
    PUBLISH_STABLE_VERSION=true
  fi
fi

if [[ "$PUBLISH_STABLE_VERSION" = "true" ]]; then
  exec sbt +clean +publishSigned sonatypeBundleRelease
else
  exec sbt +clean +publishSigned
fi
