#!/usr/bin/env bash

cd "$(dirname $0)/../../" || exit 1
if ! [ -f "./.github/env/pgp-secret" ]; then
    echo "ERROR: malformed project directory!" >&2
    exit 2
fi

sudo apt-get update && sudo apt-get -y install gnupg2
mkdir ~/.gnupg && chmod 700 ~/.gnupg
echo use-agent >> ~/.gnupg/gpg.conf
echo pinentry-mode loopback >> ~/.gnupg/gpg.conf
echo allow-loopback-pinentry >> ~/.gnupg/gpg-agent.conf
chmod 600 ~/.gnupg/*
echo RELOADAGENT | gpg-connect-agent
cat "./.github/env/pgp-secret" | base64 --decode | gpg --import --no-tty --batch --yes
