/*
 * Copyright (c) 2014-2017 by The Monix Project Developers.
 * See the project homepage at: https://monix.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.typesafe.tools.mima.core._
import com.typesafe.tools.mima.core.ProblemFilters.exclude

/** Backwards compatibility is preserved for public APIs only, not for
  * package-private APIs.
  *
  * These filters out package-private binary incompatible changes.
  */
object MimaFilters {
  /** `monix-execution` <= 2.2.4 */
  lazy val executionChangesFor_2_2_4 = Seq(
    exclude[IncompatibleMethTypeProblem]("monix.execution.cancelables.CompositeCancelable.this")
  )

  /** `monix-eval` <= 2.2.4 */
  lazy val evalChangesFor_2_2_4 = Seq(
    // Related to issue: https://github.com/monix/monix/issues/313
    exclude[DirectMissingMethodProblem]("monix.eval.internal.TaskFromFuture.apply")
  )

  /** `monix-eval` 2.3.0 */
  lazy val evalChangesFor_2_3_0 = Seq(
    exclude[DirectMissingMethodProblem]("monix.eval.Task.internalStartTrampolineRunLoop"),
    exclude[MissingClassProblem]("monix.eval.Coeval$BindSuspend"),
    exclude[MissingClassProblem]("monix.eval.Coeval$BindSuspend$"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task#MemoizeSuspend.execute"),
    exclude[MissingTypesProblem]("monix.eval.Task$Context$"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task#Eval.f"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval.trampoline")
  )

  /** `monix-reactive` <= 2.2.4 */
  lazy val reactiveChangesFor_2_2_4 = Seq(
    exclude[MissingTypesProblem]("monix.reactive.internal.operators.ConcatMapObservable$FlatMapState$WaitComplete$"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable#FlatMapState#WaitComplete.apply"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable#FlatMapState#WaitComplete.copy"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable#FlatMapState#WaitComplete.this"),
    exclude[MissingTypesProblem]("monix.reactive.internal.operators.MapTaskObservable$FlatMapState$WaitComplete$"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable#FlatMapState#WaitComplete.apply"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable#FlatMapState#WaitComplete.copy"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable#FlatMapState#WaitComplete.this"),
    exclude[MissingClassProblem]("monix.reactive.internal.operators.MapAsyncParallelObservable$MapAsyncParallelSubscriber")
  )

  /** `monix-reactive` 2.3.0 */
  lazy val reactiveChangesFor_2_3_0 = Seq(
    exclude[DirectMissingMethodProblem]("monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.secondaryQueue"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observers.buffers.AbstractBackPressuredBufferedSubscriber.primaryQueue"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observers.buffers.ConcurrentQueue.unbounded"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$CompleteConsumer$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$HeadOptionConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$CancelledConsumer$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$FromObserverConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$IndexedSubscriber"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$ForeachConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$HeadConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$MapAsyncConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$FoldLeftAsyncConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$State"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$ForeachAsyncConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$FirstNotificationConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$MapConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$Available"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$Waiting"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$Available$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$Waiting$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$FoldLeftConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$IndexedSubscriber$"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$ContraMapConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$CreateConsumer"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$LoadBalanceConsumer$AsyncQueue"),
    exclude[MissingClassProblem]("monix.reactive.Consumer$RaiseErrorConsumer"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ReactiveObservable.this"),
    exclude[MissingTypesProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber.onError"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber.onSubscribe"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber.onComplete"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber.onNext"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.rstreams.SubscriberAsReactiveSubscriber.this"),
    exclude[MissingClassProblem]("monix.reactive.internal.rstreams.SyncSubscriberAsReactiveSubscriber$")
  )

  /** `monix-execution` 3.0.0 */
  lazy val execChangesFor_3_0_0 = Seq(
    exclude[DirectMissingMethodProblem]("monix.execution.Scheduler#Extensions.executeLocal"),
    exclude[DirectMissingMethodProblem]("monix.execution.cancelables.StackedCancelable.popAndCollapse"),
    exclude[DirectMissingMethodProblem]("monix.execution.schedulers.ExecuteExtensions.executeLocal"),
    exclude[MissingClassProblem]("monix.execution.schedulers.package"),
    exclude[MissingClassProblem]("monix.execution.schedulers.package$"),
    exclude[MissingClassProblem]("monix.execution.schedulers.package$ExecutionModel$"),
    exclude[IncompatibleResultTypeProblem]("monix.execution.FutureUtils.transformWith")
  )

  /** `monix-eval` 3.0.0 */
  lazy val evalChangesFor_3_0_0 = Seq(
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval#Once.runAttempt"),
    exclude[MissingClassProblem]("monix.eval.Coeval$Attempt"),
    exclude[MissingClassProblem]("monix.eval.TaskInstances$TypeClassInstances"),
    exclude[IncompatibleResultTypeProblem]("monix.eval.TaskInstances.nondeterminism"),
    exclude[ReversedMissingMethodProblem]("monix.eval.TaskInstances.catsInstances"),
    exclude[InheritedNewAbstractMethodProblem]("monix.eval.TaskInstances2.catsEffectInstances"),
    exclude[InheritedNewAbstractMethodProblem]("monix.eval.TaskInstances1.determinism"),
    exclude[MissingClassProblem]("monix.eval.Coeval$TypeClassInstances"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.typeClassInstances"),
    exclude[IncompatibleResultTypeProblem]("monix.eval.Task.nondeterminism"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.dematerializeAttempt"),
    exclude[DirectMissingMethodProblem]("monix.eval.Task.materializeAttempt"),
    exclude[IncompatibleMethTypeProblem]("monix.eval.Task.runAsync"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval#Always.runAttempt"),
    exclude[MissingTypesProblem]("monix.eval.Coeval$Error"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval#Error.runAttempt"),
    exclude[MissingClassProblem]("monix.eval.Coeval$Attempt$"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval.dematerializeAttempt"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval.runAttempt"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval.materializeAttempt"),
    exclude[MissingTypesProblem]("monix.eval.Coeval$Now"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval#Now.runAttempt"),
    exclude[DirectMissingMethodProblem]("monix.eval.Coeval.typeClassInstances"),
    exclude[IncompatibleResultTypeProblem]("monix.eval.internal.CoevalRunLoop.start")
  )

  /** `monix-react` 3.0.0 */
  lazy val reactiveChangesFor_3_0_0 = Seq(
    exclude[DirectMissingMethodProblem]("monix.reactive.Pipe.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.Observable.typeClassInstances"),
    exclude[DirectMissingMethodProblem]("monix.reactive.Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.Observable.foldWhileL"),
    exclude[ReversedMissingMethodProblem]("monix.reactive.Observable.foldWhileLeftL"),
    exclude[MissingClassProblem]("monix.reactive.Observable$TypeClassInstances"),
    exclude[DirectMissingMethodProblem]("monix.reactive.subjects.Subject.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.subjects.Subject.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.subjects.Subject.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.EchoObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.EchoObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.EchoObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.UpstreamTimeoutObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.UpstreamTimeoutObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.UpstreamTimeoutObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#After.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#After.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#After.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryCountedObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryCountedObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryCountedObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DownstreamTimeoutObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DownstreamTimeoutObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DownstreamTimeoutObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferWithSelectorObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferWithSelectorObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferWithSelectorObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DebounceObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DebounceObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DebounceObservable.foldWhileF"),
    exclude[MissingClassProblem]("monix.reactive.internal.operators.FoldWhileObservable"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionByTimespanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionByTimespanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionByTimespanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapAsyncParallelObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapAsyncParallelObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapAsyncParallelObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionWithTriggerObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionWithTriggerObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelaySubscriptionWithTriggerObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MergeMapObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MergeMapObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MergeMapObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SubscribeOnObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SubscribeOnObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SubscribeOnObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ThrottleLastObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ThrottleLastObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ThrottleLastObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryIfObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryIfObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRetryIfObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ExecuteOnObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ExecuteOnObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ExecuteOnObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FoldLeftObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FoldLeftObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FoldLeftObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferIntrospectiveObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferIntrospectiveObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferIntrospectiveObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchMapObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchMapObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchMapObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ScanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ScanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ScanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RepeatSourceObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RepeatSourceObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RepeatSourceObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RestartUntilObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RestartUntilObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.RestartUntilObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ObserveOnObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ObserveOnObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ObserveOnObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRecoverWithObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRecoverWithObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnErrorRecoverWithObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.ConcatMapObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeLeftByTimespanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeLeftByTimespanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeLeftByTimespanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchIfEmptyObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchIfEmptyObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.SwitchIfEmptyObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropByTimespanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropByTimespanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropByTimespanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FlatScanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FlatScanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.FlatScanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayOnCompleteObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayOnCompleteObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayOnCompleteObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayBySelectorObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayBySelectorObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayBySelectorObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnCancelTriggerErrorObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnCancelTriggerErrorObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.OnCancelTriggerErrorObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferTimedObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferTimedObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.BufferTimedObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.WithLatestFromObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.WithLatestFromObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.WithLatestFromObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#Before.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#Before.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscribeObservable#Before.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayByTimespanObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayByTimespanObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DelayByTimespanObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeUntilObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeUntilObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.TakeUntilObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropUntilObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropUntilObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DropUntilObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.MapTaskObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.PipeThroughObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.PipeThroughObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.PipeThroughObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscriptionCancelObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscriptionCancelObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DoOnSubscriptionCancelObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DumpObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DumpObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.operators.DumpObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip5Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip5Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip5Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithForkObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithForkObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithForkObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IteratorAsObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IteratorAsObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IteratorAsObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest3Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest3Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest3Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ErrorObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ErrorObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ErrorObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.PipeThroughSelectorObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.PipeThroughSelectorObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.PipeThroughSelectorObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest4Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest4Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest4Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest6Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest6Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest6Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EmptyObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EmptyObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EmptyObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.StateActionObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.StateActionObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.StateActionObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.InputStreamObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.InputStreamObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.InputStreamObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest5Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest5Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest5Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.AsyncStateActionObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.AsyncStateActionObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.AsyncStateActionObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedRateObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedRateObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedRateObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IterableAsObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IterableAsObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IterableAsObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CharsReaderObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CharsReaderObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CharsReaderObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip6Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip6Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip6Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatedValueObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatedValueObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatedValueObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.DeferObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.DeferObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.DeferObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RunnableObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RunnableObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RunnableObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatEvalObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatEvalObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatEvalObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CreateObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CreateObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CreateObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.UnsafeCreateObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.UnsafeCreateObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.UnsafeCreateObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest2Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest2Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.CombineLatest2Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip3Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip3Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip3Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FirstStartedObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FirstStartedObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FirstStartedObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ReactiveObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ReactiveObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ReactiveObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedDelayObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedDelayObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.IntervalFixedDelayObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatOneObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatOneObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RepeatOneObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalAlwaysObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalAlwaysObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalAlwaysObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithModelObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithModelObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ExecuteWithModelObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RangeObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RangeObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.RangeObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalOnceObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalOnceObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.EvalOnceObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NowObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NowObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NowObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip4Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip4Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip4Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TailRecMObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TailRecMObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TailRecMObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Interleave2Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Interleave2Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Interleave2Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip2Observable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip2Observable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.Zip2Observable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ConsObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ConsObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.ConsObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TaskAsObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TaskAsObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.TaskAsObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FutureAsObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FutureAsObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.FutureAsObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.LinesReaderObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.LinesReaderObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.LinesReaderObservable.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NeverObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NeverObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.internal.builders.NeverObservable.foldWhileF"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.MultipleSubscribersException"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.CompositeException"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.CompositeException$"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.MultipleSubscribersException$"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.BufferOverflowException"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.DownstreamTimeoutException"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.UpstreamTimeoutException"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.UpstreamTimeoutException$"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.BufferOverflowException$"),
    exclude[MissingClassProblem]("monix.reactive.exceptions.DownstreamTimeoutException$"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.CachedObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.CachedObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.CachedObservable.foldWhileF"),
    exclude[MissingClassProblem]("monix.reactive.observables.ObservableLike$DeprecatedMethods$"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.ObservableLike.DeprecatedMethods"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.GroupedObservable#Implementation.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.GroupedObservable#Implementation.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.GroupedObservable#Implementation.foldWhileF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.ObservableLike.foldWhileF"),
    exclude[ReversedMissingMethodProblem]("monix.reactive.observables.ObservableLike.intersperse"),
    exclude[ReversedMissingMethodProblem]("monix.reactive.observables.ObservableLike.intersperse"),
    exclude[ReversedMissingMethodProblem]("monix.reactive.observables.ObservableLike.foldWhileLeftF"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.RefCountObservable.runWith"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.RefCountObservable.foldWhileL"),
    exclude[DirectMissingMethodProblem]("monix.reactive.observables.RefCountObservable.foldWhileF"),
    exclude[MissingClassProblem]("monix.reactive.observables.ObservableLike$DeprecatedMethods")
  )
}
