val scalaJSVersion = Option(System.getenv("SCALAJS_VERSION")).filter(_.nonEmpty).getOrElse("1.1.1")

addSbtPlugin("org.scala-js"              % "sbt-scalajs"             % scalaJSVersion)
addSbtPlugin("com.jsuereth"              % "sbt-pgp"                 % "2.0.1")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"              % "0.4.3")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                 % "0.3.7")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin"         % "0.7.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-git"                 % "1.0.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"            % "3.9.4")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"              % "5.6.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"            % "2.4.0")
addSbtPlugin("com.github.tkawachi"       % "sbt-doctest"             % "0.9.6")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"           % "1.6.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"            % "0.15.0")
addSbtPlugin("net.bzzt"                  % "sbt-reproducible-builds" % "0.24")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"            % "0.1.13")
