addSbtPlugin("org.scala-js"       %  "sbt-scalajs"           % "0.6.11")
addSbtPlugin("com.jsuereth"       %  "sbt-pgp"               % "1.0.0")
addSbtPlugin("com.github.gseitz"  %  "sbt-release"           % "1.0.0")
addSbtPlugin("com.eed3si9n"       %  "sbt-unidoc"            % "0.3.3")
addSbtPlugin("pl.project13.scala" %  "sbt-jmh"               % "0.2.6")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.3.5")
