#!/usr/bin/env ruby

def exec(cmd)
  abort("Error encountered, aborting") unless system(cmd)
end

puts "CI=#{ENV['CI']}"
puts "TRAVIS_BRANCH=#{ENV['TRAVIS_BRANCH']}"
puts "TRAVIS_TAG=#{ENV['TRAVIS_TAG']}"
puts "TRAVIS_PULL_REQUEST=#{ENV['TRAVIS_PULL_REQUEST']}"
puts "PUBLISH=#{ENV['PUBLISH']}"
puts

unless ENV['CI'] == 'true'
  abort("ERROR: Not running on top of Travis, aborting!")
end

unless ENV['PUBLISH'] == 'true'
  puts "Publish is disabled"
  exit
end

version = nil
branch = if ENV["TRAVIS_TAG"] && !ENV["TRAVIS_TAG"].empty?
  ENV["TRAVIS_TAG"] 
else
  ENV['TRAVIS_BRANCH']
end

puts "Detected branch or tag: " + branch
unless branch =~ /^v(\d+\.\d+\.\d+(?:[-.]\w+)?)$/ ||
  (branch == "snapshot" && ENV['TRAVIS_PULL_REQUEST'] == 'false')

  puts "Only publishing on the `publish` branch, or for version tags " +
       "and not for pull requests or other branches, exiting!"
  exit 0
else
  version = $1
  puts "Version branch detected: #{version}" if version
end

# Forcing a change to the root directory, if not there already
Dir.chdir(File.absolute_path(File.join(File.dirname(__FILE__), "..")))

exec("openssl aes-256-cbc -K #{ENV['encrypted_4413938994d3_key']} -iv #{ENV['encrypted_4413938994d3_iv']} -in project/.gnupg/pubring.gpg.enc -out project/.gnupg/pubring.gpg -d")
exec("openssl aes-256-cbc -K #{ENV['encrypted_4257a4a5aee2_key']} -iv #{ENV['encrypted_4257a4a5aee2_iv']} -in project/.gnupg/secring.gpg.enc -out project/.gnupg/secring.gpg -d")

# Go, go, go
exec("sbt -J-Xmx6144m release")
