name: manual-publish

on:
  workflow_dispatch:
    inputs:
      ref_to_publish:
        description: 'Ref (branch or tag)'
        required: true
        default: 'refs/heads/main'
      stable_version:
        description: 'Stable version? (true=staging, false=snapshot)'
        required: true
        default: "true"

jobs:
  publish:
    name: Publish to Sonatype (Request)

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 100
          ref: ${{ github.event.inputs.ref_to_publish }}

      - uses: actions/setup-java@v5
        with:
          cache: 'sbt'
          java-version: 17
          distribution: 'temurin'

      - name: .github/scripts/release
        run: |
          .github/scripts/release
        env:
          PGP_KEY_HEX: ${{ secrets.PGP_KEY_HEX }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PUBLISH_STABLE_VERSION: ${{ github.event.inputs.stable_version }}
          GITHUB_REF: ${{ github.event.inputs.ref_to_publish }}
