name: manual-publish

on:
  workflow_dispatch:
    inputs:
      ref_to_publish:
        description: 'Git ref. Stable releases require refs/tags/vX.Y.Z'
        required: true
      stable_version:
        description: 'Stable release (version must not end in -SNAPSHOT)'
        required: true
        type: boolean
        default: true

jobs:
  publish:
    name: Publish to Maven Central

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 100
          ref: ${{ github.event.inputs.ref_to_publish }}

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: .github/scripts/release
        run: |
          .github/scripts/release
        env:
          PGP_KEY_HEX: ${{ secrets.PGP_KEY_HEX }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          PUBLISH_STABLE_VERSION: ${{ github.event.inputs.stable_version }}
          RELEASE_REF: ${{ github.event.inputs.ref_to_publish }}
