name: Renovate

on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 09:00 UTC
    - cron: "0 9 * * 1"

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create automation token
        id: automation-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Renovate
        uses: renovatebot/github-action@v46.2.5
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ steps.automation-token.outputs.token }}
        # env:
        #   LOG_LEVEL: debug
